name: dom_marino_app
description: Aplicativo para menu e compras na Pizzaria Dom Marino.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: '^1.0.9'
  smooth_star_rating: '1.0.2'
  http: ^0.12.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.11.1+12
  flutter_staggered_grid_view: ^0.3.0
  sqflite: ^1.1.7+2
  path_provider: ^1.4.0
  intl: ^0.16.0
  dio: ^3.0.8
  flutter_facebook_login: ^3.0.0
  keyboard_visibility: ^0.5.2
  google_sign_in: ^4.1.1
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.0
  mask_text_input_formatter: ^1.0.5
#  shared_preferences: ^0.5.6+1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - images/
#    - images/logo_icon_wide_minor.png
#    - images/loading_pizza_faster.gif
#    - images/main_bg.png
#    - images/title_logo_icon_wide_minor.png
#    - images/leading_logo_icon_wide.png
#    - images/menu.png
#    - images/favorites.png
#    - images/cart.png
#    - images/orders.png
#    - images/profile.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Fryo
      fonts:
        - asset: fonts/Fryo.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
